module.exports = {
  version: '0.1',
  language: 'en',
  minWordLength: 4,
  words: [],
  ignorePaths: [
    '**/*.svg',
    '**/*.sh',
    '**/*.conf',
    '**/*.png',
    '**/*.json',
    '**/*.lock',
    '**/*.ttf',
    '**/*.otf',
    '**/*.woff',
    '**/*.ogg',
    '**/*.yml',
    '**/*.yaml',
    'config/**/*',
    'docker/**/*',
    'public/**/*',
    'scripts/**/*',
    '.browserslistrc',
    '.cz-config.js',
    '.babelrc.js',
    '.stylelintrc.js',
    '.gitignore',
    '.eslintrc.js',
    'README.md',
  ],
};
